# Generated by Django 5.1.2 on 2024-10-25 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotelPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom du package')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix')),
                ('room_type', models.CharField(choices=[('single', 'Simple'), ('double', 'Double'), ('suite', 'Suite')], max_length=255, verbose_name='Type de chambre')),
                ('number_of_rooms', models.PositiveIntegerField(verbose_name='Nombre de chambres')),
                ('hotel_rating', models.DecimalField(decimal_places=1, max_digits=2, verbose_name="Évaluation de l'hôtel")),
                ('meal_plan', models.CharField(choices=[('half_board', 'Demi-pension'), ('full_board', 'Pension complète'), ('all_inclusive', 'Tout inclus')], max_length=255, verbose_name='Type de pension')),
                ('facilities', models.TextField(blank=True, null=True, verbose_name="Installations de l'hôtel")),
                ('number_of_adults', models.PositiveIntegerField(verbose_name="Nombre d'adultes")),
                ('number_of_children', models.PositiveIntegerField(blank=True, null=True, verbose_name="Nombre d'enfants")),
                ('children_ages', models.CharField(blank=True, help_text='Séparer les âges des enfants par des virgules', max_length=255, null=True, verbose_name='Âge des enfants')),
            ],
            options={
                'verbose_name': 'Package Hôtel',
                'verbose_name_plural': 'Packages Hôtel',
            },
        ),
        migrations.CreateModel(
            name='TentPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom du package')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix')),
                ('tent_size', models.CharField(max_length=255, verbose_name='Taille de la tente')),
                ('number_of_tents', models.PositiveIntegerField(verbose_name='Nombre de tentes')),
                ('tent_amenities', models.TextField(blank=True, null=True, verbose_name='Équipements de la tente')),
                ('camp_location', models.CharField(max_length=255, verbose_name='Lieu du campement')),
            ],
            options={
                'verbose_name': 'Package Tente',
                'verbose_name_plural': 'Packages Tente',
            },
        ),
        migrations.CreateModel(
            name='VIPPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom du package')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix')),
                ('vip_access', models.BooleanField(default=False, verbose_name='Accès VIP')),
                ('private_driver', models.BooleanField(default=False, verbose_name='Chauffeur privé')),
                ('luxury_amenities', models.TextField(blank=True, null=True, verbose_name='Services de luxe')),
                ('exclusive_experience', models.TextField(blank=True, null=True, verbose_name='Expérience exclusive')),
                ('special_requests', models.TextField(blank=True, null=True, verbose_name='Demandes spéciales')),
            ],
            options={
                'verbose_name': 'Package VIP',
                'verbose_name_plural': 'Packages VIP',
            },
        ),
        migrations.CreateModel(
            name='SpecialEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_code', models.CharField(max_length=100, unique=True, verbose_name="Code de l'événement")),
                ('title', models.CharField(max_length=200, verbose_name="Titre de l'événement")),
                ('location', models.CharField(max_length=255, verbose_name="Lieu de l'événement")),
                ('duration', models.PositiveIntegerField(verbose_name="Nombre de jours de l'événement")),
                ('group_size', models.PositiveIntegerField(verbose_name='Taille du groupe')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix')),
                ('currency', models.CharField(choices=[('USD', 'Dollar Américain'), ('EUR', 'Euro'), ('TND', 'Dinar Tunisien')], max_length=3, verbose_name='Devise')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('start_time', models.TimeField(verbose_name='Heure de début')),
                ('end_time', models.TimeField(verbose_name='Heure de fin')),
                ('description', models.TextField(blank=True, null=True, verbose_name="Description de l'événement")),
                ('include', models.TextField(blank=True, null=True, verbose_name="Inclus dans l'événement")),
                ('exclude', models.TextField(blank=True, null=True, verbose_name="Exclus de l'événement")),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de contact')),
                ('contact_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Téléphone de contact')),
                ('organizer', models.CharField(blank=True, max_length=200, null=True, verbose_name='Organisateur')),
                ('website', models.URLField(blank=True, null=True, verbose_name="Site Web de l'événement")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('hotel_pack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='specialevent.hotelpack', verbose_name='Package Hôtel')),
                ('tent_pack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='specialevent.tentpack', verbose_name='Package Tente')),
                ('vip_pack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='specialevent.vippack', verbose_name='Package VIP')),
            ],
        ),
        migrations.CreateModel(
            name='TourDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField(verbose_name='Numéro du jour')),
                ('morning_activity', models.TextField(blank=True, null=True, verbose_name='Activités du matin')),
                ('afternoon_activity', models.TextField(blank=True, null=True, verbose_name="Activités de l'après-midi")),
                ('evening_activity', models.TextField(blank=True, null=True, verbose_name='Activités du soir')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_days', to='specialevent.specialevent', verbose_name='Événement')),
            ],
            options={
                'ordering': ['day_number'],
                'unique_together': {('event', 'day_number')},
            },
        ),
    ]
